### ISSUE TITLE
Weird issue when trying to do OTA updates !

### ISSUE THREAD

**Issue by vincegre** [esphome/ESPHome#191]
Hi

I have upgraded one of my D1 Mini (running an other firmware previously !) to esphomeyaml. The config file has been made with Wizard and just added a GPIO declaration that works fine with HA ;)
I did first upload through USB port but before closing back the box and putting back the D1 Mini in the heater I wanted to check OTA is working fine and it's not ! I get that truncated error while trying to do OTU (is it just not enough memory in D1 Mini for OTA or something else ?

Thanks

> Retrieving maximum program size .pioenvs/chaudiere/firmware.elf
> Checking size .pioenvs/chaudiere/firmware.elf
> Memory Usage -> http://bit.ly/pio-memory-usage
> DATA:    [=====     ]  46.2% (used 37888 bytes from 81920 bytes)
> PROGRAM: [===       ]  32.4% (used 338499 bytes from 1044464 bytes)
> ================================== [SUCCESS] Took 1.68 seconds ==================================
> INFO [esphomeyaml.__main__] Successfully compiled program.
> INFO [esphomeyaml.__main__] Uploading binary...
> INFO [esphomeyaml.espota] Starting on 0.0.0.0:54895
> INFO [esphomeyaml.espota] Upload size: 342640
> INFO [esphomeyaml.espota] Sending invitation to chaudiere.local 
> 
> ERROR [esphomeyaml.espota] Bad Answer: ERR: ERROR[8]: Flash config wrong rea
> vincen@fixe:~/Bureau/esphomelib$ 

**Operating environment (Hass.io/Docker/pip/etc.):**
Linux Ubuntu 18.04.1

**ESP (ESP32/ESP8266/Board/Sonoff):**
ESP8266

**Comment by OttoWinter** [comment]
What `board` did you put in your configuration?

That error indicates that the firmware you uploaded previously has been created with a flash size that does not match the actual flash size of the ESP.

So you need to:

 Step 1: Make sure the `board` option is correct.
 Step 2: Re-upload via USB. OTA won't work as this value needs to be checked against the value of the firmware that is already on the ESP.

**Comment by vincegre** [comment]
```

> What board did you put in your configuration?
> That error indicates that the firmware you uploaded previously has been created with a flash size that does not match the actual flash size of the ESP.

here is what I putted in yaml file:

```
esphomeyaml:
  name: chaudiere
  platform: ESP8266
  board: d1_mini
```

> So you need to:
> Step 1: Make sure the board option is correct.
> Step 2: Re-upload via USB. OTA won't work as this value needs to be checked against the value of the firmware that is already on the ESP.

Here are pictures of board as I'm not sure what's wrong here, I selected the correct chipset and board according to indications on board no ?
![img_20181017_150222](https://user-images.githubusercontent.com/3164888/47088171-1fd98100-d21e-11e8-9aaa-11aa4302da91.jpg)
![img_20181017_150240](https://user-images.githubusercontent.com/3164888/47088173-1fd98100-d21e-11e8-8bf0-476a429a0e95.jpg)

**Comment by OttoWinter** [comment]
Puh... I don't know what it could be then - never seen that error message before.

The error also comes from the arduino framework (`ArduinoOTA` library), so I tend to believe maybe the flash chip is broken somehow.

**Comment by vincegre** [comment]
@OttoWinter I agree with you on Flasf chip that would be defective but why then the error would appear only when I try an OTA update. If I flash it in USB it always works and from what I have seen till now it works (it's not crashing after few minutes or random errors as I would expect with a defective flash chip !

**Comment by ladefoged81** [comment]
Not sure if this is related, but I've just added BLE to an ESP32 module (so the file size is a lot bigger than without BLE)
Compiled and uploaded via USB without problems.
After this I can't do OTA updates. It stops between 0% and 3%
Still works fine with USB uploads.

**Comment by OttoWinter** [comment]
@ladefoged81 Yes, that's a known issue with ESP32s and their socket connections. For some reason the tcp nodelay breaks things there.

**Comment by ladefoged81** [comment]
@OttoWinter Is there a fix/workaround for the ESP32?
