### ISSUE TITLE
OTA 100% but still fails :(

### ISSUE THREAD

**Issue by vincegre** [esphome/ESPHome#356]
Operating environment (Hass.io/Docker/pip/etc.): Hassio with ESPHome plugin in hassio 32 bits on Pi3B+ (updated at 1.10.1)
ESP (ESP32/ESP8266/Board/Sonoff): D1 Mini (but problem same with other ESP)
Affected component: OTA update
Description of problem: On an ESP running already 1.10.0 firmware, I try to do an OTA to push it at 1.10.1 but it fails. The upload of the firmware goes up to 100% but after it gets an error and fails. The ESP becomes unresponsive and I have to power reboot it and then it goes back online but still with old firmware ! ~~I could reproduce with different ESP (so not specific to D1 Mini used here).~~ Works perfectly on a Sonoff that is supposed not to have enough memory for OTA but failing on D1 Mini....
Noticed also that unless the OTA failed for that device and so it's still running 1.10.0 the update Avalaible is no more present for that device in list of devices in ESPHome gui in HA !

![otafail](https://user-images.githubusercontent.com/3164888/51374972-e0644e80-1b04-11e9-8a5c-f8267b3d0909.png)

**Comment by OttoWinter** [comment]
See the error please:
> Error: Finishing update failed. **See the MQTT/USB logs for more information.**

**Comment by OttoWinter** [comment]
Closing for no response. Please re-open if error still exists and with more info
