### ISSUE TITLE
Crash after startup

### ISSUE THREAD

**Issue by JustGav** [esphome/ESPHome#363]
**Operating environment (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266/Board/Sonoff):**

**Affected component:**

**Description of problem:**

After flashing the unit appears to go into a boot loop when monitoring via serial, I've re-compiled the firmware, erased the flash on multiple devices, and reprogrammed after recompiling.  It appears to occur on sonoff, esp8266 and nodemcu boards.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
```

**Traceback (if applicable):**

```

```

**Additional information:**

[0;32m[I][mqtt.client:209]: MQTT Connected![0m
[0;36m[D][api:531]: Client 'esphomeyaml v1.10.1 (192.168.XX.56)' connected successfully![0m

Panic /root/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/core_esp8266_main.cpp:103 __yield

ctx: sys 
sp: 3fffea70 end: 3fffffb0 offset: 01b0

>>>stack>>>
3fffec20:  00000000 00000000 40106896 1f3b645a 
<<<stack<<<

 ets Jan  8 2013,rst cause:1, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
vbb28d4a3
~ld

**Comment by OttoWinter** [comment]
Did you read the warning here? https://esphomelib.com/esphomeyaml/components/api.html
