### ISSUE TITLE
Sending IR Code

### ISSUE THREAD

**Issue by DarrenCarterSA** [esphome/esphome#476]
Good day.

I need some assistance here. Previously with Tasmota I was able to control my TV by sending the command '{ "Protocol": "NEC","Bits": 32,"Data": "0x6F900FF" }' to Tasmota.

ESPHome's NEC protocol seems to want an address and command parameter. I'm not too sure where this address parameter comes from?

Regards,

Darren Carter

**Comment by OttoWinter** [comment]
https://github.com/esphome/esphome/issues/430
